name = giant_biome_trees
title = Giant Biome Trees
description = Genera un árbol gigante proceduralmente único y de muy baja densidad en los biomas por defecto.
depends = default
author = LendroX
version = 1.0.0