name = giant_biome_trees
title = Giant Biome Trees
description = Genera árboles gigantes, muy grandes y poco frecuentes en los biomas de Luanti.
depends = default
author = LendroX
version = 1.0.1